Update trigger-deletion.yml

diff --git a/.github/workflows/trigger-deletion.yml b/.github/workflows/trigger-deletion.yml
--- a/.github/workflows/trigger-deletion.yml
+++ b/.github/workflows/trigger-deletion.yml
@@ -1,39 +1,33 @@
-name: Delete Minutes Ago Workflow Runs
-
+name: Delete Workflow Run by passing runid as a parameter
 on:
   workflow_dispatch:
     inputs:
-      minutes_ago:
-        description: 'Number of minutes ago'
+      run_id:
+        description: 'Workflow Run ID to Delete'
         required: true
 
 jobs:
-  delete_old_runs:
+  delete_run:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Calculate Date Threshold
-        run: |
-          # Calculate the time threshold (minutes ago)
-          MINUTES_AGO=$((${{ github.event.inputs.minutes_ago }} * 60)) # Convert to seconds
-          THRESHOLD=$(date -u -d "@$(( $(date +%s) - $MINUTES_AGO ))" +"%Y-%m-%dT%H:%M:%SZ")
-          echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
-      - name: Get Workflow Runs
-        id: get_runs
+      - name: Delete Workflow Run
         run: |
-          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
-          RUNS=$(curl -s "$API_URL")
+          # Set the base URL of your workflow management system's API
+          API_BASE_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs"
 
-          # Filter runs older than the specified time threshold
-          OLDER_RUNS=$(echo "$RUNS" | jq --arg THRESHOLD "$THRESHOLD" '.workflow_runs[] | select(.created_at <= $THRESHOLD) | .id')
+          # Get the run ID from the workflow_dispatch input
+          RUN_ID="${{ github.event.inputs.run_id }}"
 
-      - name: Display OLDER_RUNS
-        run: |
-              # Loop through and display each identified run using echo
-              for run_id in $OLDER_RUNS; do
-                echo "Processing run: $run_id"
-                echo "Command: echo 'OLDER_RUN: $run_id'"
-                echo "----"
-                echo "OLDER_RUN: $run_id"
-              done
+          # Construct the URL for deleting the workflow run
+          DELETE_URL="$API_BASE_URL/runs/$RUN_ID"
+
+          # Send an HTTP DELETE request to delete the run
+          curl -X DELETE $DELETE_URL
+          if [ $? -eq 0 ]; then
+            echo "Workflow run $RUN_ID deleted successfully."
+          else
+            echo "Failed to delete workflow run $RUN_ID."
+          fi
